apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodi-ui
  namespace: nodi
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - nodi.example.com
      secretName: nodi-tls
  rules:
    - host: nodi.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nodi-ui
                port:
                  name: http
