apiVersion: v1
kind: Service
metadata:
  name: nodi-backend
  namespace: nodi
spec:
  selector:
    app.kubernetes.io/name: nodi-backend
    app.kubernetes.io/part-of: nodi
  ports:
    - name: http
      port: 8787
      targetPort: http
  type: ClusterIP
